### ISSUE TITLE
how to update mock/json file

### ISSUE THREAD

**Issue by weihaoysgs** [vace/wechatapp-news-reader#11]
hello, thanks very much your contribution.
i am tempt using your frame work to contribute a app, but when i modify the json file in the mock dir, the content in the page is not change, can you give me a help, thanks very much!

**Comment by vace** [comment]
Look it up here：https://github.com/vace/wechatapp-news-reader/blob/master/utils/api.js#L4

```
// you can use your own domain name
const DOMAIN = 'https://h5.ahmq.net/demo/miniapp-static-api/mock'
```
